version: 2

project_name: trane

builds:
  - id: trane
    main: ./main.go
    binary: trane
    goos: [darwin, linux, windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    builds: [trane]
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: false
    files:
      - LICENSE
      - README.md
      - go.mod

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"
